apiVersion: apps/v1
kind: Deployment

metadata:

  name: lung-cancer-api

  namespace: lung-cancer


spec:

  replicas: 2

  selector:

    matchLabels:

      app: lung-cancer-api


  template:

    metadata:

      labels:

        app: lung-cancer-api


    spec:

      containers:

        - name: lung-cancer-api

          image: YOUR_AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/lung-cancer-mlops:latest

          ports:

            - containerPort: 8000

          resources:

            requests:

              cpu: "100m"

              memory: "128Mi"

            limits:

              cpu: "500m"

              memory: "512Mi"

          readinessProbe:

            httpGet:

              path: /health

              port: 8000

            initialDelaySeconds: 10

            periodSeconds: 10

          livenessProbe:

            httpGet:

              path: /health

              port: 8000

            initialDelaySeconds: 20

            periodSeconds: 20