apiVersion: v1
kind: Service
metadata:
  name: lung-cancer-service
  namespace: lung-cancer

spec:
  type: LoadBalancer

  selector:
    app: lung-cancer-api

  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
