apiVersion: v1
kind: Service

metadata:

  name: lung-cancer-service

  namespace: lung-cancer


spec:

  selector:

    app: lung-cancer-api


  ports:

    - protocol: TCP

      port: 80

      targetPort: 8000


  type: LoadBalancer