name: CD

on:

  push:

    branches:
      - main


permissions:

  contents: write

  id-token: write


env:

  AWS_REGION: ap-south-1

  ECR_REPOSITORY: lung-cancer-mlops

  IMAGE_TAG: ${{ github.sha }}


jobs:

  deploy:

    runs-on: ubuntu-latest


    steps:


      # ------------------------------------------------
      # Checkout
      # ------------------------------------------------

      - name: Checkout code

        uses: actions/checkout@v4


      # ------------------------------------------------
      # Configure AWS
      # ------------------------------------------------

      - name: Configure AWS credentials

        uses: aws-actions/configure-aws-credentials@v4

        with:

          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

          aws-region: ${{ env.AWS_REGION }}


      # ------------------------------------------------
      # Login to ECR
      # ------------------------------------------------

      - name: Login to Amazon ECR

        id: login-ecr

        uses: aws-actions/amazon-ecr-login@v2


      # ------------------------------------------------
      # Get ECR registry
      # ------------------------------------------------

      - name: Set ECR registry

        run: |

          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV


      # ------------------------------------------------
      # Build Docker image
      # ------------------------------------------------

      - name: Build Docker image

        run: |

          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            .

          docker tag \
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            $ECR_REGISTRY/$ECR_REPOSITORY:latest


      # ------------------------------------------------
      # Push Docker image
      # ------------------------------------------------

      - name: Push Docker image

        run: |

          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          docker push \
            $ECR_REGISTRY/$ECR_REPOSITORY:latest


      # ------------------------------------------------
      # Update Kubernetes manifest
      # ------------------------------------------------

      - name: Update deployment image

        run: |

          sed -i \
          "s|image:.*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|" \
          k8s/deployment.yaml


      # ------------------------------------------------
      # Commit GitOps change
      # ------------------------------------------------

      - name: Commit Kubernetes manifest

        run: |

          git config user.name "github-actions"

          git config user.email "github-actions@github.com"

          git add k8s/deployment.yaml

          git commit -m "Update lung cancer image to $IMAGE_TAG" || echo "No changes"

          git push