name: Lung Cancer MLOps CI

on:
  workflow_dispatch:

env:
  MLFLOW_TRACKING_URI: http://32.198.38.148:5000
  AWS_REGION: ap-south-1
  S3_BUCKET: lung-cancer-mlops-dinesh-202612

permissions:
  contents: read
  id-token: write

jobs:

  ml-pipeline:

    runs-on: ubuntu-latest

    steps:

      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3. Dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. AWS OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::821656895219:role/GitHubActionsLungCancerRole
          aws-region: ap-south-1

      # 5. AWS test
      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      # 6. Preprocess
      - name: Preprocess data
        run: |
          python src/preprocess.py

      # 7. Train
      - name: Train model
        run: |
          python src/train.py

      # 8. Evaluate
      - name: Evaluate model
        run: |
          python src/evaluate.py

      # 9. Inference
      - name: Run inference
        run: |
          python src/inference.py

      # 10. Tests
      - name: Run tests
        run: |
          pytest -v

      # 11. Upload processed data
      - name: Upload processed datasets to S3
        run: |
          aws s3 cp artifacts/train.csv \
            s3://${S3_BUCKET}/artifacts/train.csv

          aws s3 cp artifacts/test.csv \
            s3://${S3_BUCKET}/artifacts/test.csv

      # 12. Upload model
      - name: Upload model to S3
        run: |
          aws s3 cp model/model.pkl \
            s3://${S3_BUCKET}/models/model.pkl

      # 13. Verify S3
      - name: Verify S3 artifacts
        run: |
          echo "Artifacts:"
          aws s3 ls s3://${S3_BUCKET}/artifacts/

          echo "Models:"
          aws s3 ls s3://${S3_BUCKET}/models/
